apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reflector-secrets-binding
subjects:
  - kind: ServiceAccount
    name: reflector
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: reflector-secrets
  apiGroup: rbac.authorization.k8s.io

