apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-backend-deployment
  namespace: financial
spec:
  selector:
    matchLabels:
      app: financial-backend-deployment
  template:
    metadata:
      labels:
        app: financial-backend-deployment
    spec:
      containers:
      - name: financial-backend
        image: ghcr.io/felipecisotto/financial-backend:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9464
          name: otel
        envFrom:
        - configMapRef:
            name: financial-backend-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
