apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: financial-backend
  namespace: financial
spec:
  imageRepositoryRef:
    name: financial-backend
  policy:
    semver:
      range: '>=0.0.0'
