apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: financial-backend
  namespace: financial
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.felipecisotto.com.br`) && PathPrefix(`/financial`)
      priority: 1000
      kind: Rule
      middlewares:
        - name: financial-path-rewrite
      services:
        - name: financial-backend
          port: 80
  tls:
    secretName: certificates
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: financial-path-rewrite
  namespace: financial
spec:
  stripPrefix:
    prefixes:
      - "/financial"
    forceSlash: false
