apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - image-policy.yaml
  - image-repository.yaml
  - image-update-automation.yaml
  - hpa.yaml

images:
  - name: ghcr.io/felipecisotto/financial-backend
    newName: ghcr.io/felipecisotto/financial-backend
    newTag: latest
