apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: financial-backend-otel
  namespace: monitoring
  labels:
    podmonitorscrape: "true"
    app: financial-backend
spec:
  selector:
    matchLabels:
      app: financial-backend-service
  namespaceSelector:
    matchNames:
      - financial
  endpoints:
    - port: otel
      interval: 15s
      path: /metrics
      scrapeTimeout: 10s
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_label_app]
          regex: financial-backend-service
          action: keep
        - sourceLabels: [__meta_kubernetes_endpoint_port_name]
          regex: otel
          action: keep
