apiVersion: v1
kind: Service
metadata:
  name: financial-backend
  namespace: financial
spec:
  selector:
    app: financial-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
