apiVersion: v1
kind: Service
metadata:
  name: financial-backend
  namespace: financial
  labels:
    app: financial-backend-service
spec:
  selector:
    app: financial-backend-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: otel
      protocol: TCP
      port: 9464
      targetPort: 9464
