apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: financial-backend-otel
  namespace: financial
  labels:
    release: prometheus
    podmonitorscrape: "true"
    app: financial-backend
spec:
  selector:
    matchLabels:
      app: financial-backend
  namespaceSelector:
    matchNames:
      - financial
  endpoints:
    - port: otel
      interval: 15s
      path: /metrics
      scrapeTimeout: 10s
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_container_name]
          targetLabel: container
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
