apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: sealed-secrets
      version: 2.16.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

