apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: monitoring
      version: "0.44.x"
  values:
    mode: deployment
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
      processors:
        batch: {}
      exporters:
        prometheus:
          endpoint: "0.0.0.0:8889"
        logging:
          verbosity: detailed
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus, logging]
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]
    service:
      type: ClusterIP
    ports:
      prometheus:
        enabled: true
        containerPort: 8889
        servicePort: 8889
        protocol: TCP
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi 