apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: "58.x"
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      enabled: false
    prometheus:
      prometheusSpec:
        podMonitorNamespaceSelector:
          matchLabels:
            podmonitorscrape: "true"
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        scrapeInterval: 15s
        scrapeTimeout: 10s
        retention: 15d
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
    kube-state-metrics:
      enabled: true
      metricLabelsAllowlist:
        - nodes=[*]
        - pods=[*]
        - services=[*]
        - namespaces=[*]
    prometheus-node-exporter:
      enabled: true
