apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "6.56.0"
  values:
    service:
      type: ClusterIP
    adminUser: admin
    adminPassword: admin

    # Configurações para persistência efêmera
    persistence:
      enabled: false

    # Configuração de logs para debug
    grafana.ini:
      log:
        mode: console
        level: debug
      paths:
        provisioning: /etc/grafana/provisioning
      dashboards:
        min_refresh_interval: 5s
        default_home_dashboard_path: /var/lib/grafana/dashboards/financial-backend-golden-signals.json

    # Configuração para montar os dashboards a partir de JSON
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'financial'
          orgId: 1
          folder: 'Financial'
          type: file
          disableDeletion: false
          allowUiUpdates: true
          updateIntervalSeconds: 5
          options:
            path: /var/lib/grafana/dashboards
            foldersFromFilesStructure: false

    # Configuração dos sidecars para datasources e dashboards
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "1"
        searchNamespace: ALL
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL
        provider:
          foldersFromFilesStructure: false

    # Volumes não são necessários quando usando sidecar
    extraVolumeMounts: []
    extraVolumes: []
