apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "6.56.0"
  values:
    service:
      type: ClusterIP
    adminUser: admin
    adminPassword: admin

    # Configurações para persistência efêmera
    persistence:
      enabled: false

    # Configuração de logs para debug
    grafana.ini:
      log:
        mode: console
        level: debug
      paths:
        provisioning: /etc/grafana/provisioning

    # Configuração para montar os dashboards a partir de JSON
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          allowUiUpdates: true
          updateIntervalSeconds: 5
          options:
            path: /var/lib/grafana/dashboards
            foldersFromFilesStructure: true

    # Configuração dos sidecars para datasources e dashboards
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL
        folderAnnotation: grafana_folder
        provider:
          foldersFromFilesStructure: true
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "1"
        searchNamespace: ALL

    # Volumes não são necessários quando usando sidecar
    extraVolumeMounts: []
    extraVolumes: []
