apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "6.56.0"
  values:
    service:
      type: ClusterIP
    adminUser: admin
    adminPassword: admin
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "1"
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        # Allow discovery in all namespaces for dashboards
        searchNamespace: ALL
        provider:
          allowUiUpdates: true

    persistence:
      enabled: true
      type: pvc
      accessModes:
        - ReadWriteOnce
      size: 4Gi
