apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.felipecisotto.com.br`)
      kind: Rule
      services:
        - name: grafana
          port: 80
  tls:
    secretName: certificates

