---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: smart-review
spec:
  encryptedData:
    DATABASE_URL: AgBqLe88KgZax8VHtIBIgV5m9laTNQ0A/2GEAwdnmlW7QRH3KZLWsE2lOPHDLKBIi69N2wYgdKPHYXOHxOYHrc5FBL30TeiPFBoaqHtVbAckHGPIkxerPofh0620F4bc0VeMTTJ5SYilq4hd6rkDD9573+u7j/6G2C2vp0IQjMGomfC8Fppcamgqtv+Nv0B1W/SyECR9+Dj36iZUUws9YHKSsnJmM/FcpGw8i+OjoxVqJiya9BTOIzBaBGYRAzpoEfpobMIrq6oJg/e7oa2vwJIu67aOj0RUuzdcSOV+qpYWw7Yw+FPZwbqlFdXLCmq1fNXWQ4YfE0qaDHdSRYQb3uFuf8DOyiMQkQsqoNtRJuTFqbICnG3BWcN7VQTbPR3G5PGQrQ4SSFrf8shXVfaK3OrZVOdPdeDRFS8lI5YEtR58quPb3fL38X55D25o2FB2sF6HaNO5dgVDKrZETmFsEHyHYYTRGFdrfJRx9h8lmAnfaL08nJfbf/RQUrRhI7ms4S2LRcbCD3GAW6Vdx0VRM+crDlypvoKcNIJLnTmhWBvcccPURn0JXRx5Qw6ZVC0IkZ0rCioiED0pvnOjeejIpYIwne7ANIKFX2Hj64LWkyGv4hZdU/iyumhSRGEkHSa9rBXUKLA0RBx4v13gkV/Zmpc20SuNcJD5o5zit58KjDRfXuGPs4fVYGOitkI/h7P3JTJyIY7rs0o4vFIawcVcJBWWziuMjLXpnOd1OUXwEx3ihLCs/6oJUDlan546JqNjTgVUEq/1HT9+vgLzl14=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secret
      namespace: smart-review
