apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  dnsNames:
    - "felipecisotto.com.br"
    - "dashboard.felipecisotto.com.br"
    - "status.felipecisotto.com.br"
  secretName: certificates
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  secretTemplate:
    labels:
      replicate: "true"
    annotations:
      # Permit for miror creation in the following namespace.
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "apps,monitoring"
      
      # Automatically create a miror in the following namespace.
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "apps,monitoring"
