apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager
  namespace: default
spec:
  dnsNames:
    - "registry.felipecisotto.com.br"
  secretName: certificates
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
