apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  dnsNames:
    - "felipecisotto.com.br"
    - "dashboard.felipecisotto.com.br"
    - "status.felipecisotto.com.br"
  secretName: certificates
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
