apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - home-assistant-sealed-token.yaml
  - home-assistant-scrape.yaml
  - mosquitto-config.yaml
  - mqtt-ingress.yaml
