apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pv-config
  namespace: apps
  labels:
    app: homeassistant-label
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-pvc
  namespace: apps
  labels:
    app: homeassistant-label
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-log-pvc
  namespace: apps
  labels:
    app: homeassistant-label
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
