{
 "title": "Casa",
 "tags": [
  "homeassistant",
  "casa"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Gasto de energia",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(entity) (homeassistant_sensor_power_w)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Baterias",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{entity!~\"sensor.iphone_battery_level|sensor.iphone_de_lavinia_battery_level\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Umidade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg by(friendly_name) (homeassistant_sensor_humidity_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(friendly_name) (homeassistant_climate_current_temperature_celsius)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(friendly_name) (homeassistant_sensor_temperature_celsius)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}