apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: apps
spec:
  type: NodePort
  selector:
    service: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    nodePort: 30379