apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: heimdall
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: heimdall
      version: "8.X"
      sourceRef:
        kind: HelmRepository
        name: heimdall
        namespace: apps
  values: 
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 500Mi
