apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: heimdall-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dashboard.felipecisotto.com.br`)
      kind: Rule
      services:
        - name: heimdall
          port: 80
  tls:
    certResolver: cert-manager
