apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Lista de recursos que devem ser gerenciados
resources:
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - pvc.yaml

# Patches ou modificações opcionais (se necessário)
