apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: apps
spec:
  selector:
    app: open-webui
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080 
    - name: otel
      protocol: TCP
      port: 4318
      targetPort: 4318