apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open-webui-otel
  namespace: apps
  labels:
    podmonitorscrape: "true"
    app: open-webui
spec:
  selector:
    matchLabels:
      app: open-webui
  namespaceSelector:
    matchNames:
      - apps
  endpoints:
    - port: otel
      interval: 15s
      path: /metrics
      scrapeTimeout: 10s
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_label_app]
          regex: open-webui
          action: keep
        - sourceLabels: [__meta_kubernetes_endpoint_port_name]
          regex: otel
          action: keep
