apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - pvc.yaml
  - mysql-deployment.yaml
  - mysql-pvc.yaml
  - secret.yaml
  - service.yaml
  - ingress.yaml