apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mysql-secret
  namespace: apps
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # rootpassword (base64)
  mysql-password: d29yZHByZXNzcGFzcw==  # wordpresspass (base64)